# Generated by Django 5.1.6 on 2025-02-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('near_month_price', models.FloatField()),
                ('far_month_price', models.FloatField()),
                ('storage_fee', models.FloatField()),
                ('trading_fee', models.FloatField()),
                ('delivery_fee', models.FloatField()),
                ('capital_cost', models.FloatField()),
                ('tax', models.FloatField()),
                ('vat', models.FloatField()),
                ('stamp_duty', models.FloatField()),
                ('cost_tax', models.FloatField()),
                ('price_spread', models.FloatField(blank=True, null=True)),
                ('arbitrage_cost', models.FloatField(blank=True, null=True)),
                ('net_spread', models.FloatField(blank=True, null=True)),
                ('annual_return', models.FloatField(blank=True, null=True)),
                ('delivery_date', models.DateField()),
                ('inter_period_time', models.IntegerField()),
            ],
        ),
    ]
