# Generated by Django 5.1.6 on 2025-03-13 05:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbitragedata',
            old_name='delivery_date',
            new_name='first_delivery_date',
        ),
        migrations.AddField(
            model_name='arbitragedata',
            name='far_month_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arbitragedata',
            name='near_month_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arbitragedata',
            name='second_delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
