# Generated by Django 5.1.6 on 2025-03-21 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0002_knowledgebasefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('vector', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_app.knowledgebasefile')),
            ],
        ),
    ]
