# Generated by Django 5.1.6 on 2025-03-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0004_alter_productdata_warehouse'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productdata',
            constraint=models.UniqueConstraint(fields=('batch_number', 'update_date'), name='unique_batch_date'),
        ),
    ]
