# Generated by Django 5.1.6 on 2025-03-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0008_productdata_warehouse_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='warehouse_area',
            field=models.CharField(blank=True, default='内地', max_length=50),
        ),
    ]
