// src/config.ts
export const apiUrl = 'http://localhost:8000/api';

export const productionRegions = [
    // { label: '-请选择产区-', value: '' }, 
    { label: '南疆', value: '南疆' },
    { label: '北疆', value: '北疆' },
    { label: '东疆', value: '东疆' },
    { label: '兵团', value: '兵团' }
];

export const productionPlaces = [
    // { label: '-请选择产地-', value: '' }, 
    { label: '阿克苏', value: '阿克苏' },
    { label: '八师', value: '八师' },
    { label: '巴州', value: '巴州' },
    { label: '博州', value: '博州' },
    { label: '昌吉', value: '昌吉' },
    { label: '二师', value: '二师' },
    { label: '哈密', value: '哈密' },
    { label: '和田', value: '和田' },
    { label: '喀什', value: '喀什' },
    { label: '克拉玛', value: '克拉玛' },
    { label: '克州', value: '克州' },
    { label: '库新沙', value: '库新沙' },
    { label: '六师', value: '六师' },
    { label: '农八师', value: '农八师' },
    { label: '农二师', value: '农二师' },
    { label: '农六师', value: '农六师' },
    { label: '农七师', value: '农七师' },
    { label: '农三师', value: '农三师' },
    { label: '农十三', value: '农十三' },
    { label: '农十四', value: '农十四' },
    { label: '农五师', value: '农五师' },
    { label: '七师', value: '七师' },
    { label: '三师', value: '三师' },
    { label: '十三师', value: '十三师' },
    { label: '四师', value: '四师' },
    { label: '塔城', value: '塔城' },
    { label: '吐鲁番', value: '吐鲁番' },
    { label: '乌鲁木齐', value: '乌鲁木齐' },
    { label: '五师', value: '五师' },
    { label: '一师', value: '一师' },
    { label: '伊犁', value: '伊犁' }
];

export const productionTypes = [
    // { label: '-请选择类型-', value: '' }, 
    { label: '机采', value: '机采' },
    { label: '手摘', value: '手摘' },
    { label: '长绒', value: '长绒' },   
];

export const productionWarehousesArea = [
    // { label: '-请选择类型-', value: '' }, 
    { label: '内地', value: '内地' },
    { label: '新疆', value: '新疆' },
];

export const productionWarehouses = [
    // { label: '-请选择仓库-', value: '' }, 
    { label: '库尔勒汇', value: '库尔勒汇' },
    { label: '奎屯农资', value: '奎屯农资' },
    { label: '兵棉宏泰', value: '兵棉宏泰' },
    { label: '阿拉尔鹏', value: '阿拉尔鹏' },
    { label: '库尔勒恒', value: '库尔勒恒' },
    { label: '新疆中新', value: '新疆中新' },
    { label: '阿克苏银', value: '阿克苏银' },
    { label: '伽师瑞利', value: '伽师瑞利' },
    { label: '新疆西部', value: '新疆西部' },
    { label: '乌市诸天', value: '乌市诸天' },
    { label: '巴楚棉储', value: '巴楚棉储' },
    { label: '阿克苏益', value: '阿克苏益' },
    { label: '奎屯陆德', value: '奎屯陆德' },
    { label: '阿克苏铁', value: '阿克苏铁' },
    { label: '巴楚润金', value: '巴楚润金' },
    { label: '库尔勒银', value: '库尔勒银' },
    { label: '兵棉润泽', value: '兵棉润泽' },
    { label: '中储库尔', value: '中储库尔' },
    { label: '奎屯银棉', value: '奎屯银棉' },
    { label: '阿克苏兵', value: '阿克苏兵' },
    { label: '中供乌苏', value: '中供乌苏' },
    { label: '新疆象道', value: '新疆象道' },
    { label: '益美达仓', value: '益美达仓' },
    { label: '昌吉华嵘', value: '昌吉华嵘' },
    { label: '阿克苏华', value: '阿克苏华' },
    { label: '新疆天运', value: '新疆天运' },
    { label: '乌市棉麻', value: '乌市棉麻' },
    { label: '大河沿二', value: '大河沿二' },
    { label: '哈密供销', value: '哈密供销' },
    { label: '巴州尉棉', value: '巴州尉棉' },
    { label: '中锦胡杨', value: '中锦胡杨' },
    { label: '郓城众誉', value: '郓城众誉' },
    { label: '新疆天运', value: '新疆天运' },
    { label: '乌市棉麻', value: '乌市棉麻' },
    { label: '大河沿二', value: '大河沿二' },
    { label: '哈密供销', value: '哈密供销' },
    { label: '巴州尉棉', value: '巴州尉棉' },
    { label: '中锦胡杨', value: '中锦胡杨' },
    { label: '郓城众誉', value: '郓城众誉' },
    { label: '新疆锦葵', value: '新疆锦葵' },
    { label: '奎屯中亚', value: '奎屯中亚' },
    { label: '新疆天运', value: '新疆天运' },
    { label: '乌市棉麻', value: '乌市棉麻' },
    { label: '大河沿二', value: '大河沿二' },
    { label: '哈密供销', value: '哈密供销' },
    { label: '巴州尉棉', value: '巴州尉棉' },
    { label: '中锦胡杨', value: '中锦胡杨' },
    { label: '郓城众誉', value: '郓城众誉' },
    { label: '新疆锦葵', value: '新疆锦葵' },
    { label: '奎屯中亚', value: '奎屯中亚' },
    { label: '莎车中联', value: '莎车中联' },
    { label: '博州新棉', value: '博州新棉' },
    { label: '江苏银隆', value: '江苏银隆' },
    { label: '乌苏亿佳', value: '乌苏亿佳' },
    { label: '河南豫棉', value: '河南豫棉' },
    { label: '中棉山东', value: '中棉山东' },
    { label: '滨州中纺', value: '滨州中纺' },
    { label: '前海仓储', value: '前海仓储' },
    { label: '菏泽巨野', value: '菏泽巨野' },
    { label: '江阴协丰', value: '江阴协丰' },
    { label: '诚通西部', value: '诚通西部' },
    { label: '菏泽棉麻', value: '菏泽棉麻' },
    { label: '金棉仓储', value: '金棉仓储' },
    { label: '农资奎屯', value: '农资奎屯' },
    { label: '湖北三三', value: '湖北三三' },
    { label: '厦门象屿', value: '厦门象屿' },
    { label: '新疆港汇', value: '新疆港汇' },
    { label: '奎屯新亚', value: '奎屯新亚' },
    { label: '菏泽转运', value: '菏泽转运' },
    { label: '石河子通', value: '石河子通' },
    { label: '湖北局三', value: '湖北局三' },
    { label: '菏泽经贸', value: '菏泽经贸' },
    { label: '新乡富华', value: '新乡富华' },
    { label: '库尔勒大', value: '库尔勒大' },
    { label: '陕西大唐', value: '陕西大唐' },
    { label: '乌市米泉', value: '乌市米泉' },
    { label: '辉县常青', value: '辉县常青' },
    { label: '邱县汇力', value: '邱县汇力' },
    { label: '冠县德润', value: '冠县德润' },
    { label: '临西方沛', value: '临西方沛' },
    { label: '江阴联运', value: '江阴联运' },
    { label: '舞钢中昌', value: '舞钢中昌' },
    { label: '山东平原', value: '山东平原' },
    { label: '中棉南宫', value: '中棉南宫' },
    { label: '新乡九州', value: '新乡九州' },
    { label: '淄博粮食', value: '淄博粮食' },
    { label: '衡水棉麻', value: '衡水棉麻' },
    { label: '中集邯郸', value: '中集邯郸' },
    { label: '河南四三', value: '河南四三' },
    { label: '中棉河南', value: '中棉河南' },
    { label: '兰溪华储', value: '兰溪华储' },
    { label: '新乡恒瑞', value: '新乡恒瑞' },
    { label: '国储浙江', value: '国储浙江' },
    { label: '临清华茂', value: '临清华茂' },
    { label: '黄梅小池', value: '黄梅小池' },
    { label: '河南物流', value: '河南物流' },
    { label: '福建闽龙', value: '福建闽龙' },
    { label: '南阳红棉', value: '南阳红棉' },
    { label: '南通供销', value: '南通供销' },
    { label: '银海农佳', value: '银海农佳' },
    { label: '响丰纺织', value: '响丰纺织' },
    { label: '中供南通', value: '中供南通' },
    { label: '浙江国储', value: '浙江国储' },
    { label: '张家港昊', value: '张家港昊' },
    { label: '海安正元', value: '海安正元' },
    { label: '湖北五三', value: '湖北五三' },
    { label: '江阴站', value: '江阴站' },
    { label: '湖北景天', value: '湖北景天' },
    { label: '武城兴宏', value: '武城兴宏' }
];