# Generated by Django 5.2 on 2025-05-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CottonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('length_strength_params', models.JSONField(verbose_name='长度/比强参数')),
                ('micronaire_params', models.JSONField(verbose_name='马克隆值参数')),
                ('hand_machine_length_params', models.JSONField(verbose_name='手扯长度/机扯长度参数')),
                ('processing_quality_params', models.JSONField(verbose_name='轧工质量参数')),
                ('origin_params', models.JSONField(verbose_name='产地参数')),
                ('fiber_quality_params', models.JSONField(verbose_name='纤维品质参数')),
                ('rejection_criteria', models.JSONField(verbose_name='拒收标准')),
                ('policy_params', models.JSONField(verbose_name='政策性参数')),
            ],
            options={
                'verbose_name': '棉花参数配置',
                'verbose_name_plural': '棉花参数配置',
                'ordering': ['-created_at'],
            },
        ),
    ]
