# Generated by Django 5.2 on 2025-05-09 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_type', models.CharField(choices=[('length', '长度参数'), ('strength', '比强参数'), ('micronaire', '马克隆值'), ('rejection', '拒收标准')], max_length=20, unique=True)),
                ('values', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CottonCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='certs/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '计算中'), ('completed', '已完成'), ('failed', '已失败')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('warehouse', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='calculate_a_status_a8cf09_idx'), models.Index(fields=['batch_number'], name='calculate_a_batch_n_855904_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('color_grade', models.CharField(blank=True, max_length=20)),
                ('avg_length', models.FloatField(null=True)),
                ('avg_micronaire', models.FloatField(null=True)),
                ('avg_strength', models.FloatField(null=True)),
                ('details', models.JSONField(default=dict)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='calculate_app.cottoncertificate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
