# Generated by Django 5.1.6 on 2025-03-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0002_alter_productdata_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='color_grade',
            field=models.CharField(max_length=50),
        ),
    ]
