# Generated by Django 5.1.6 on 2025-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0003_alter_productdata_color_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='warehouse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
