# Generated by Django 5.1.6 on 2025-03-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0005_productdata_unique_batch_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productdata',
            name='unique_batch_date',
        ),
        migrations.AddConstraint(
            model_name='productdata',
            constraint=models.UniqueConstraint(fields=('batch_number', 'update_date', 'quotation_method'), name='unique_batch_date_quatation'),
        ),
    ]
