# Generated by Django 5.1.6 on 2025-03-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0010_alter_productdata_warehouse_area'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productdata',
            index=models.Index(fields=['update_date'], name='idx_update_date'),
        ),
    ]
