# Generated by Django 5.1.6 on 2025-03-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0011_productdata_idx_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='batch_product_area',
            field=models.CharField(default='新疆', max_length=50),
        ),
    ]
