# Generated by Django 5.1.6 on 2025-03-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0012_productdata_batch_product_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='batch_product_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
